version: "3.9"

services:
  ai-service:
    build: ./ai-service
    container_name: aura_ai
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - aura-net

  dashboard:
    build: ./dashboard
    container_name: aura_dashboard
    restart: always
    ports:
      - "5173:80"
    networks:
      - aura-net

  flowise:
    image: flowiseai/flowise:latest
    container_name: aura_flowise
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - flowise_data:/root/.flowise
    environment:
      - PORT=3000
      - FLOWISE_USERNAME=admin
      - FLOWISE_PASSWORD=admin
    networks:
      - aura-net

  postgres:
    image: postgres:15
    container_name: aura_postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - aura-net


  qdrant:
    image: qdrant/qdrant:latest
    container_name: aura_qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - aura-net

volumes:
  postgres_data:
  flowise_data:
  qdrant_data:

networks:
  aura-net:
    driver: bridge
